### ISSUE TITLE
Plusieurs textes différents pour la partie "dons"

### ISSUE THREAD

**Issue by trebmuh** [LibraZiK/lzk_donate_tip#16]
Il y a beaucoup de texte actuellement dans la partie "don" (la partie basse) de la fenêtre, et j'ai quelques choses à ajouter qui traînent dans des recoins de ma tête.
Une possibilité d'avoir plusieurs textes différents et de les afficher l'un après l'autre serait super (comme la partie "astuces").

**Comment by Houston4444** [comment]
Humm, si je comprends bien tu voudrais avoir 1 fenêtre avec 2 mini groupes, l'un pour les astuces et l'autre pour d'autres informations (dons, autres...) sur le même modèle (avec navigation précédent/suivant).
Ça ne me pose pas particulièrement de problème à mettre en place, par contre ça me paraît un peu confus côté utilisateur.
Il existe probablement une solution plus adaptée.
En fait j'aurai besoin de connaître ce que tu voudrais mettre en alternative au texte de dons, et est-ce qu'il y a vraiment plusieurs textes alternatifs. De plus, si les dons se retrouvent noyés parmi d'autres choses, il y a sans doute plus de chances pour que l'utilisateur ne les voie pas, ou les considèrent comme une info parmi d'autres.

**Comment by trebmuh** [comment]
> Humm, si je comprends bien tu voudrais avoir 1 fenêtre avec 2 mini groupes, l'un pour les astuces et l'autre pour d'autres informations (dons, autres...) sur le même modèle (avec navigation précédent/suivant).

Oui. Sauf les boutons de navigation, je n'en veux pas pour la partie "don".


>  Ça ne me pose pas particulièrement de problème à mettre en place, par contre ça me paraît un peu confus côté utilisateur.

En quoi ça serait plus confus que ce qu'il y a actuellement ? Point de vue utilisateur, c'est la même chose sauf que le message de "don" n'est pas toujours le même.

**Comment by trebmuh** [comment]
J'ai fusionné, mais il y a quelque chose qui me gêne dans l'implémentation actuelle.
Lorsque l'on clique sur une des flèches (préc/suiv) du texte d'astuce, cela influe également sur le texte de don.
Je souhaiterai que l'utilisateur puisse naviguer parmis les astuces avec préc/suiv (ce qui est déjà le cas), mais je voudrais que le texte de don ne change pas avec.
Dans mon idée, le texte de don change à chaque fois que l'écran est affiché, mais pas avec les flêches préc/suiv.

**Comment by trebmuh** [comment]
Ceci a été corrigé dans https://github.com/LibraZiK/lzk_donate_tip/commit/811b908f202fb7214069ee4ad5d01367b9d02422
Merci @Houston4444 !
Je referme ici.
